markdown: redcarpet
paginate: 30
paginate_path: ":num"
pygments: true
permalink: /:title/

name: DevGrow.com
title: DevGrow - Design, Develop, Grow
author: DevGrow.com
description: Online journal dedicated to providing resources on the design, development and growth of websites
url: http://devgrow.com

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile', 'Capfile', 'Guardfile']