name: DevGrow - Design. Develop. Grow.
markdown: redcarpet
paginate: 30
paginate_path: ":num"
pygments: true
permalink: /:title/

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile', 'Capfile', 'Guardfile']